# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 16:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Author email')),
                ('profile_url', models.URLField(blank=True, null=True, verbose_name='Profile URL')),
            ],
            options={
                'verbose_name_plural': 'Authors',
                'ordering': ('name', 'email'),
                'verbose_name': 'Author',
            },
            managers=[
                ('site_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='title')),
                ('url', models.URLField(db_index=True, unique=True, verbose_name='Url')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blogs',
                'ordering': ('title', 'url'),
                'verbose_name': 'Blog',
            },
            managers=[
                ('site_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Category Title')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date created')),
            ],
            options={
                'verbose_name_plural': 'Feed Categories',
                'ordering': ('title', 'date_created'),
                'verbose_name': 'Feed Category',
            },
        ),
        migrations.CreateModel(
            name='Enclosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(max_length=20, verbose_name='Length')),
                ('mime_type', models.CharField(db_index=True, max_length=50, verbose_name='MIME type')),
                ('link', models.URLField(db_index=True, max_length=500, verbose_name='Url')),
            ],
            options={
                'verbose_name_plural': 'Post Enclosures',
                'ordering': ('post', 'mime_type', 'link'),
                'verbose_name': 'Post Enclosure',
            },
            managers=[
                ('site_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, unique=True, verbose_name='Url')),
                ('title', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Title')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='Subtitle')),
                ('rights', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rights')),
                ('info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Infos')),
                ('language', models.CharField(blank=True, max_length=50, null=True, verbose_name='Language')),
                ('guid', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='Global Unique Identifier')),
                ('icon_url', models.URLField(blank=True, null=True, verbose_name='Icon URL')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('etag', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Etag')),
                ('last_modified', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last modified')),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='Last checked')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='If disabled, this feed will not be further updated.', verbose_name='Is active')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planet.Blog')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planet.Category')),
            ],
            options={
                'verbose_name_plural': 'Feeds',
                'ordering': ('title',),
                'verbose_name': 'Feed',
            },
            managers=[
                ('site_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FeedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel', models.CharField(db_index=True, max_length=50, verbose_name='Relation')),
                ('mime_type', models.CharField(db_index=True, max_length=50, verbose_name='MIME type')),
                ('link', models.URLField(db_index=True, max_length=500, verbose_name='Url')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planet.Feed')),
            ],
            options={
                'verbose_name_plural': 'Feed Links',
                'ordering': ('feed', 'rel', 'mime_type'),
                'verbose_name': 'Feed Link',
            },
            managers=[
                ('site_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Url')),
                ('version', models.CharField(blank=True, max_length=200, null=True, verbose_name='Version')),
            ],
            options={
                'verbose_name_plural': 'Generators',
                'ordering': ('name', 'version'),
                'verbose_name': 'Generator',
            },
            managers=[
                ('site_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('url', models.URLField(db_index=True, max_length=1000, verbose_name='Url')),
                ('guid', models.CharField(db_index=True, max_length=32, verbose_name='Guid')),
                ('content', models.TextField(verbose_name='Content')),
                ('comments_url', models.URLField(blank=True, null=True, verbose_name='Comments URL')),
                ('date_modified', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date modified')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ('-date_created', '-date_modified'),
                'verbose_name': 'Post',
            },
            managers=[
                ('site_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PostAuthorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_contributor', models.BooleanField(default=False, verbose_name='Is Contributor?')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date created')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planet.Author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planet.Post')),
            ],
            options={
                'verbose_name_plural': 'Post Author Data',
                'ordering': ('author', 'post', 'is_contributor'),
                'verbose_name': 'Post Author Data',
            },
        ),
        migrations.CreateModel(
            name='PostLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel', models.CharField(db_index=True, max_length=50, verbose_name='Relation')),
                ('mime_type', models.CharField(db_index=True, max_length=50, verbose_name='MIME type')),
                ('link', models.URLField(db_index=True, max_length=500, verbose_name='Url')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planet.Post')),
            ],
            options={
                'verbose_name_plural': 'Post Links',
                'ordering': ('post', 'title', 'rel'),
                'verbose_name': 'Post Link',
            },
            managers=[
                ('site_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='authors',
            field=models.ManyToManyField(through='planet.PostAuthorData', to='planet.Author'),
        ),
        migrations.AddField(
            model_name='post',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planet.Feed'),
        ),
        migrations.AlterUniqueTogether(
            name='generator',
            unique_together=set([('name', 'link', 'version')]),
        ),
        migrations.AddField(
            model_name='feed',
            name='generator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planet.Generator'),
        ),
        migrations.AddField(
            model_name='feed',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='enclosure',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planet.Post'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('feed', 'guid')]),
        ),
    ]
