# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0002_on_delete'),
        ('planet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='primary_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tagging.Tag'),
        ),
    ]
