# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0003_post_priorty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='priorty',
            new_name='priority',
        ),
    ]
