# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0004_auto_20160805_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='post',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='Priority'),
        ),
    ]
