# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0006_auto_20160805_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='shortname',
            field=models.CharField(default='', max_length=50, verbose_name='Short Name'),
            preserve_default=False,
        ),
    ]
