# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0007_generator_shortname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generator',
            name='shortname',
        ),
        migrations.AddField(
            model_name='blog',
            name='short_name',
            field=models.CharField(default='', max_length=50, verbose_name='Short Name'),
            preserve_default=False,
        ),
    ]
