# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0009_auto_20160818_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taginfo',
            name='tag',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tagging.Tag'),
        ),
    ]
