# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0010_auto_20160818_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='taginfo',
            name='ignore',
            field=models.BooleanField(default=False, verbose_name='Ignore this Tag'),
        ),
    ]
